### PR TITLE
Sync LICENSE file to same as in metadata.json (Apache-2.0)

### PR DESCRIPTION
**Pull request by juniorsysadmin**
LICENSE file is MIT but metadata.json has had Apache-2.0 for quite
some time

### CODE REVIEW

**Comment by juniorsysadmin** [comment]
Was changed to Apache-2.0 as part of puppet-community migration in https://github.com/voxpupuli/puppet-visualstudio/commit/88fa7160172c37791fa55257048f71eb3d93994a

**Comment by liamjbennett** [comment]
+1

**Comment by juniorsysadmin** [comment]
Note: One committer @liamjbennett and one approval for change in LICENSE

**Comment by juniorsysadmin** [comment]
Ready for merge/review

**Pull request merged**
